server:
  port: 8090
  context-path: /
logging:
  level: debug
  path: /data/log/website

spring:
  thymeleaf:
    encoding: utf-8
    suffix: .html
    prefix: classpath:/templates/
    content-type: text/html
  profiles:
    active: mac

---
spring:
  profiles: mac
logging:
  level: info
  path: /data/log/website

---
spring:
  profiles: windows
logging:
  level: info
  path: H:/study/data/log/website
