server:
  port: 8090
  context-path: /

spring:
  profiles:
    active: dev-windows
  thymeleaf:
    encoding: utf-8
    suffix: .html
    prefix: classpath:/templates/
    content-type: text/html
    cache: false
    mode: HTML5
logging:
  level: info
  path: /data/log/website

---
spring:
  profiles: dev-mac
logging:
  level: info
  path: /data/log/website

---
spring:
  profiles: dev-windows
logging:
  level: info
  path: H:/study/data/log/website
